import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import jsxA11y from "eslint-plugin-jsx-a11y";

export default tseslint.config(
  { ignores: ["dist"] },
  {
    extends: [
      js.configs.recommended,
      ...tseslint.configs.strict,
      // "plugin:jsx-a11y/strict",
      jsxA11y.flatConfigs.recommended,
    ],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": "error",
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      "jsx-a11y/anchor-is-valid": [
        "warn",
        {
          components: ["Link"],
          specialLink: ["hrefLeft", "hrefRight"],
          aspects: ["invalidHref", "preferButton"],
        },
      ],
      "jsx-a11y/label-has-for": ["error"],
      "jsx-a11y/label-has-associated-control": ["error"],
      "jsx-a11y/anchor-has-content": ["error"],
      "jsx-a11y/anchor-is-valid": ["error"],
      "jsx-a11y/click-events-have-key-events": ["error"],
      "jsx-a11y/no-static-element-interactions": ["error"],
      "jsx-a11y/no-autofocus": ["error"],
      "jsx-a11y/no-noninteractive-tabindex": ["error"],
      "jsx-a11y/no-noninteractive-element-interactions": ["error"],
      "jsx-a11y/role-has-required-aria-props": ["error"],
      "jsx-a11y/role-supports-aria-props": ["error"],
      "jsx-a11y/role-has-required-aria-props": ["error"],
      "jsx-a11y/role-supports-aria-props": ["error"],
      "jsx-a11y/aria-role": ["error"],
      "jsx-a11y/aria-props": ["error"],
      "jsx-a11y/aria-unsupported-elements": ["error"],
      "jsx-a11y/aria-role": ["error"],
      "jsx-a11y/aria-props": ["error"],
      "jsx-a11y/aria-unsupported-elements": ["error"],
      "jsx-a11y/anchor-is-valid": [
        "error",
        {
          components: ["Link"],
          specialLink: ["hrefLeft", "hrefRight"],
          aspects: ["invalidHref", "preferButton"],
        },
      ],
      "jsx-a11y/click-events-have-key-events": ["error"],
      "jsx-a11y/no-static-element-interactions": ["error"],
      "jsx-a11y/no-autofocus": ["error"],
      "jsx-a11y/no-noninteractive-tabindex": ["error"],
      "jsx-a11y/no-noninteractive-element-interactions": ["error"],
      "jsx-a11y/no-noninteractive-element-to-interactive-role": ["error"],
      "jsx-a11y/role-has-required-aria-props": ["error"],
      "jsx-a11y/role-supports-aria-props": ["error"],
      "jsx-a11y/role-has-required-aria-props": ["error"],
      "jsx-a11y/role-supports-aria-props": ["error"],
      "jsx-a11y/aria-role": ["error"],
      "jsx-a11y/aria-props": ["error"],
      "jsx-a11y/aria-unsupported-elements": ["error"],
      "jsx-a11y/aria-role": ["error"],
      "jsx-a11y/aria-props": ["error"],
      "jsx-a11y/aria-unsupported-elements": ["error"],
      "jsx-a11y/anchor-is-valid": [
        "error",
        {
          components: ["Link"],
          specialLink: ["hrefLeft", "hrefRight"],
          aspects: ["invalidHref", "preferButton"],
        },
      ],
      "jsx-a11y/click-events-have-key-events": ["error"],
      "jsx-a11y/no-static-element-interactions": ["error"],
      "jsx-a11y/no-autofocus": ["error"],
      "jsx-a11y/no-noninteractive-tabindex": ["error"],
      "jsx-a11y/no-noninteractive-element-interactions": ["error"],
      "jsx-a11y/no-noninteractive-element-to-interactive-role": ["error"],
      "jsx-a11y/role-has-required-aria-props": ["error"],
      "jsx-a11y/role-supports-aria-props": ["error"],
      "jsx-a11y/role-has-required-aria-props": ["error"],
      "jsx-a11y/role-supports-aria-props": ["error"],
      "jsx-a11y/aria-role": ["error"],
      "jsx-a11y/aria-props": ["error"],
      "jsx-a11y/aria-unsupported-elements": ["error"],
      "jsx-a11y/aria-role": ["error"],
      "jsx-a11y/aria-props": ["error"],
      "jsx-a11y/aria-unsupported-elements": ["error"],
      "jsx-a11y/anchor-is-valid": [
        "error",
        {
          components: ["Link"],
          specialLink: ["hrefLeft", "hrefRight"],
          aspects: ["invalidHref", "preferButton"],
        },
      ],
      "jsx-a11y/click-events-have-key-events": ["error"],
      "jsx-a11y/no-static-element-interactions": ["error"],
      "jsx-a11y/no-autofocus": ["error"],
      "jsx-a11y/no-noninteractive-tabindex": ["error"],
      "jsx-a11y/no-noninteractive-element-interactions": ["error"],
      "jsx-a11y/no-noninteractive-element-to-interactive-role": ["error"],
      "jsx-a11y/role-has-required-aria-props": ["error"],
      "jsx-a11y/role-supports-aria-props": ["error"],
      "jsx-a11y/role-has-required-aria-props": ["error"],
      "jsx-a11y/role-supports-aria-props": ["error"],
      "jsx-a11y/aria-role": ["error"],
      "jsx-a11y/aria-props": ["error"],
      "jsx-a11y/alt-text": "error",
    },
  }
);
